blog_title = "My blog"
blog_author = "Author"
base_url = "http://localhost:3000"
lang = "en"
blog_license = "CC 4.0 BY-SA"
blog_license_url = "https://creativecommons.org/licenses/by-sa/4.0/"
articles_dir = "articles"
port = 3000
truncate_lines = 15
thumbnail_show_articles = false
# social_links = [
#     "https://github.com/your-username",
#     "https://linkedin.com/in/your-username",
#     "https://twitter.com/your-username"
# ]

# [git]
# link = "https://github.com/user/repo"
# folder = ""
# assets_folder = ""
# username = "user"
# password = "pat"
# branch = "main"

