/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./templates/**/*.js",
    "./src/**/*.rs",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#5a4225",
        "background": "#fbf9f4",
        "on-error-container": "#93000a",
        "primary-container": "#2c3e50",
        "surface-container-highest": "#e4e2dd",
        "surface": "#fbf9f4",
        "secondary-fixed-dim": "#92cfee",
        "on-primary": "#ffffff",
        "secondary-container": "#a3dfff",
        "on-secondary-fixed": "#001e2b",
        "secondary-fixed": "#c0e8ff",
        "inverse-primary": "#b5c8df",
        "on-primary-container": "#96a9be",
        "on-surface": "#1b1c19",
        "surface-container-low": "#f5f3ee",
        "surface-variant": "#e4e2dd",
        "on-primary-fixed-variant": "#36485b",
        "surface-dim": "#dbdad5",
        "on-secondary-fixed-variant": "#004d66",
        "inverse-surface": "#30312e",
        "error-container": "#ffdad6",
        "on-secondary-container": "#21647f",
        "secondary": "#236580",
        "primary": "#162839",
        "outline": "#74777d",
        "surface-container-high": "#eae8e3",
        "on-background": "#1b1c19",
        "surface-bright": "#fbf9f4",
        "tertiary": "#362308",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d1e4fb",
        "on-primary-fixed": "#091d2e",
        "on-tertiary-container": "#c1a17d",
        "on-surface-variant": "#43474c",
        "primary-fixed-dim": "#b5c8df",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#291802",
        "surface-container": "#f0eee9",
        "tertiary-container": "#4e381c",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffddb7",
        "surface-tint": "#4e6073",
        "tertiary-fixed-dim": "#e3c19b",
        "inverse-on-surface": "#f2f1ec",
        "outline-variant": "#c4c6cd"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "8px",
        "stack-lg": "64px",
        "margin-mobile": "22px",
        "stack-md": "32px",
        "container-max": "800px",
        "gutter": "24px",
        "stack-sm": "12px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Playfair Display"],
        "body-md": ["Source Sans 3"],
        "headline-xl": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "body-lg": ["Source Sans 3"],
        "code-block": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg": ["Playfair Display"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "code-block": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-sm": ["13px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
