version: '3.8'

services:
  corkboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: corkboard_blog
    restart: unless-stopped
    ports:
      - "8080:3000"
    volumes:
      - ../articles:/app/articles
      - ../config.toml:/app/config.toml
    environment:
      # - PUID=1000
      # - PGID=1000
      - RUST_LOG=corkboard=info,axum=info
      - CORKBOARD_PORT=3000
      - CORKBOARD_BLOG_TITLE=My blog
      - CORKBOARD_BLOG_AUTHOR=Author
      - CORKBOARD_ARTICLES_DIR=/app/articles
      - CORKBOARD_TRUNCATE_LINES=15
      # - CORKBOARD_THUMBNAIL_SHOW_ARTICLES=false
      # - CORKBOARD_SOCIAL_LINKS=https://github.com/your-username,https://linkedin.com/in/your-username,https://twitter.com/your-username
      # - CORKBOARD_BLOG_LICENSE=CC 4.0 BY-SA
      # - CORKBOARD_BLOG_LICENSE_URL=https://creativecommons.org/licenses/by-sa/4.0/
