name: Update Golden Images

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_goldens:
    uses: ./.github/workflows/setup-goldens.yml
    with:
      override: true
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
